---
- name: Check if bash-it is available
  stat:
    path: "{{ lookup('env', 'HOME') }}/.bash_it"
  register: is_bash_it_available
- name: Install bash-it
  block:
    - name: Clone bash-it repository
      git:
        repo: "https://github.com/Bash-it/bash-it.git"
        dest: "{{ lookup('env', 'HOME') }}/.bash_it"
        clone: yes
        force: yes
        depth: 1
    - name: Install bash-it
      shell: "echo 'y' | {{ lookup('env', 'HOME') }}/.bash_it/install.sh"
      args:
        executable: /bin/bash
  when: not is_bash_it_available
- name: Set bash-it theme
  replace:
    path: "{{ lookup('env', 'HOME') }}/.bashrc"
    regexp: "export BASH_IT_THEME='(.*)'"
    replace: "export BASH_IT_THEME='{{ bash_it_theme }}'"
