---
- name: Install history hotkeys, if inputrc wasn't defined before
  blockinfile:
    state: present
    path: ~/.inputrc
    create: yes
    block: |
      "\e[A": history-search-backward
      "\e[B": history-search-forward
      "\e[C": forward-char
      "\e[D": backward-char
