---
- name: Install python3
  become: yes
  apt:
    name:
      - python3-dev
      - python3-pip
    state: latest
- name: Append pip3 package bin to PATH
  lineinfile:
    path: ~/.bashrc
    line: export PATH="${HOME}/.local/bin:${PATH}"
    regexp: export PATH=".*.${HOME}/.local/bin:${PATH}.*"
    state: present
- name: symlink /usr/bin/python -> /usr/bin/python3
  file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    state: link
  become: true
