---
- name: Install rust
  shell: >
    set -o pipefail
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    creates: "{{ lookup('env', 'HOME') }}/.cargo/bin/cargo"
