---
- name: Install VIM
  become: yes
  apt:
    name:
      - vim
    state: latest
- name: Clone Vundle VIM repository
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "{{ ansible_env.HOME }}/.vim/bundle/Vundle.vim"
    clone: yes
    force: yes
    depth: 1
- name: Config VIM
  blockinfile:
    state: present
    path: ~/.vimrc
    marker: '"{mark} ANSIBLE MANAGED BLOCK'
    create: yes
    block: |
      set nocompatible
      filetype off

      set rtp+=~/.vim/bundle/Vundle.vim
      call vundle#begin()

      Plugin 'VundleVim/Vundle.vim'

      Plugin 'preservim/nerdtree'
      Plugin 'Xuyuanp/nerdtree-git-plugin'
      Plugin 'frazrepo/vim-rainbow'
      Plugin 'vim-airline/vim-airline'
      Plugin 'tpope/vim-fugitive'
      Plugin 'Yggdroot/indentLine'
      Plugin 'rakr/vim-one'

      call vundle#end()
      filetype plugin indent on

      let g:airline#extensions#tabline#enabled = 1
      let g:airline_powerline_fonts = 1
      let g:airline#extensions#tabline#formatter = 'unique_tail'
      let g:indentLine_enabled = 1
      let g:indentLine_leadingSpaceEnabled = 1

      if (empty($TMUX))
        if (has("nvim"))
        "For Neovim 0.1.3 and 0.1.4 < https://github.com/neovim/neovim/pull/2198 >
        let $NVIM_TUI_ENABLE_TRUE_COLOR=1
        endif
        "For Neovim > 0.1.5 and Vim > patch 7.4.1799 < https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162 >
        "Based on Vim patch 7.4.1770 (`guicolors` option) < https://github.com/vim/vim/commit/8a633e3427b47286869aa4b96f2bfc1fe65b25cd >
        " < https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 >
        if (has("termguicolors"))
          set termguicolors
        endif
      endif

      set background=dark " for the dark version
      " set background=light " for the light version
      silent! colorscheme one

      map <C-b> :NERDTreeToggle<CR>

      set t_Co=256
      :set number

- name: Install VIM Vundle plugins
  shell: |
    set -o pipefail
    vim +PluginInstall +qall &> /dev/null
  args:
    executable: /bin/bash
  changed_when: False

- name: Install powerline font
  become: yes
  apt:
    name:
      - fonts-powerline
    state: latest
