---
- name: "Execute command - ({{ command }})"
  shell: |
    set -Eeo pipefail
    {{ command }}
  args:
    executable: /bin/bash
  register: command_output
  changed_when: False
- name: Check command is executable and output values
  assert:
    that: command_output.rc == 0
