---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint
platforms:
  - name: ubuntu_1804
    image: ubuntu:18.04
  - name: ubuntu_2004
    image: ubuntu:20.04
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible
