---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint
platforms:
  - name: ubuntu_2204
    image: ubuntu:22.04
  - name: ubuntu_2404
    image: ubuntu:24.04
provisioner:
  name: ansible
  log: true
  options:
    vvv: True
verifier:
  name: ansible
