---
- name: Verify
  hosts: all
  tasks:
  - name: assert command version
    include_role:
      name: assert_shell_command
    vars:
      command: "{{ item }}"
    with_items:
      - python3 --version
      - pip --version
      - vim --version
      - source ~/.cargo/env && rustup --version
      - source ~/.nvm/nvm.sh && nvm --version
      - source ~/.nvm/nvm.sh && node --version
